<a href="https://colab.research.google.com/github/227r1a0502N/502_DevopsLAB/blob/main/AirFly_Insights_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Milestone 1 – Week 1: Data Foundation and Cleaning**



**Dataset: Flight Delay & Cancellation (2019–2023)**

**STEP 1: Import Required Libraries**

In [ ]:
!pip install plotly --quiet

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

sns.set_style("whitegrid")
pd.set_option("display.max_columns", None)

**STEP 2: Create Project Folder Structure**

**STEP 3: Confirm Dataset Already Loaded**

In [ ]:
import pandas as pd

file_path = '/content/sample_data/AirFly_Insights_Data_Set.csv'
df = pd.read_csv(file_path)
display(df.head())

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,...,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",...,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",...,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",...,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",...,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",...,0.0,181.0,182.0,153.0,985.0,NaN,NaN,NaN,NaN,NaN

**DATASET UNDERSTANDING**

STEP 4: Check Dataset Size

The dataset contains ___ rows and ___ columns representing airline operational records.

In [6]:
df.shape

(3000000, 32)

**STEP 5: Check Column Names**

In [27]:
df.columns

Index(['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'DOT_CODE',
       'FL_NUMBER', 'ORIGIN', 'ORIGIN_CITY', 'DEST', 'DEST_CITY',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_DUE_CARRIER',
       'DELAY_DUE_WEATHER', 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY',
       'DELAY_DUE_LATE_AIRCRAFT'],
      dtype='object')

**SCHEMA ANALYSIS**

**STEP 6: Check Data Types**

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 32 columns):
 #   Column                   Dtype
---  ------                   -----
 0   FL_DATE                  object
 1   AIRLINE                  object
 2   AIRLINE_DOT              object
 3   AIRLINE_CODE             object
 4   DOT_CODE                 int64
 5   FL_NUMBER                int64
 6   ORIGIN                   object
 7   ORIGIN_CITY              object
 8   DEST                     object
 9   DEST_CITY                object
 10  CRS_DEP_TIME             int64
 11  DEP_TIME                 float64
 12  DEP_DELAY                float64
 13  TAXI_OUT                 float64
 14  WHEELS_OFF               float64
 15  WHEELS_ON                float64
 16  TAXI_IN                  float64
 17  CRS_ARR_TIME             int64
 18  ARR_TIME                 float64
 19  ARR_DELAY                float64
 20  CANCELLED                float64
 21  CANCELLATION_CODE        object
 22  DIVERTED                 float64
 23  CRS_ELAPSED_TIME         float64
 24  ELAPSED_TIME             float64
 25  AIR_TIME                 float64
 26  DISTANCE                 float64
 27  DELAY_DUE_CARRIER        float64
 28  DELAY_DUE_WEATHER        float64
 29  DELAY_DUE_NAS            float64
 30  DELAY_DUE_SECURITY       float64
 31  DELAY_DUE_LATE_AIRCRAFT  float64
dtypes: float64(19), int64(4), object(9)
memory usage: 732.4+ MB

object → categorical

int/float → numerical

object but looks like date → needs conversion

**STEP 7: Separate Column Types**

In [8]:
categorical_cols = df.select_dtypes(include=['object']).columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

print("Categorical Columns:")
print(categorical_cols)

print("\nNumerical Columns:")
print(numerical_cols)

Categorical Columns:
Index(['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'ORIGIN',
       'ORIGIN_CITY', 'DEST', 'DEST_CITY', 'CANCELLATION_CODE'],
      dtype='object')

Numerical Columns:
Index(['DOT_CODE', 'FL_NUMBER', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY',
       'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME',
       'ARR_TIME', 'ARR_DELAY', 'CANCELLED', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_DUE_CARRIER',
       'DELAY_DUE_WEATHER', 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY',
       'DELAY_DUE_LATE_AIRCRAFT'],
      dtype='object')

**STEP 8: Create Feature Dictionary**

In [9]:
feature_dictionary = pd.DataFrame({
    "Column_Name": df.columns,
    "Data_Type": df.dtypes.values,
    "Null_Count": df.isnull().sum().values
})

feature_dictionary

                Column_Name Data_Type  Null_Count
0                   FL_DATE    object           0
1                   AIRLINE    object           0
2               AIRLINE_DOT    object           0
3              AIRLINE_CODE    object           0
4                  DOT_CODE     int64           0
5                 FL_NUMBER     int64           0
6                    ORIGIN    object           0
7               ORIGIN_CITY    object           0
8                      DEST    object           0
9                 DEST_CITY    object           0
10             CRS_DEP_TIME     int64           0
11                 DEP_TIME   float64       77615
12                DEP_DELAY   float64       77644
13                 TAXI_OUT   float64       78806
14               WHEELS_OFF   float64       78806
15                WHEELS_ON   float64       79944
16                  TAXI_IN   float64       79944
17             CRS_ARR_TIME     int64           0
18                 ARR_TIME   float64       79942
19                ARR_DELAY   float64       86198
20                CANCELLED   float64           0
21        CANCELLATION_CODE    object     2920860
22                 DIVERTED   float64           0
23         CRS_ELAPSED_TIME   float64          14
24             ELAPSED_TIME   float64       86198
25                 AIR_TIME   float64       86198
26                 DISTANCE   float64           0
27        DELAY_DUE_CARRIER   float64     2466137
28        DELAY_DUE_WEATHER   float64     2466137
29            DELAY_DUE_NAS   float64     2466137
30       DELAY_DUE_SECURITY   float64     2466137
31  DELAY_DUE_LATE_AIRCRAFT   float64     2466137

In [12]:
import os

# Create the directory if it does not exist
os.makedirs("AirFly_Insights/reports", exist_ok=True)

feature_dictionary.to_csv("AirFly_Insights/reports/feature_dictionary.csv", index=False)

It documents:

Column name

Data type

Missing values

**MISSING VALUE STUDY**

**STEP 9: Check Null Counts**

In [13]:
df.isnull().sum().sort_values(ascending=False)

CANCELLATION_CODE          2920860
DELAY_DUE_LATE_AIRCRAFT    2466137
DELAY_DUE_CARRIER          2466137
DELAY_DUE_SECURITY         2466137
DELAY_DUE_NAS              2466137
DELAY_DUE_WEATHER          2466137
ARR_DELAY                    86198
ELAPSED_TIME                 86198
AIR_TIME                     86198
WHEELS_ON                    79944
TAXI_IN                      79944
ARR_TIME                     79942
WHEELS_OFF                   78806
TAXI_OUT                     78806
DEP_DELAY                    77644
DEP_TIME                     77615
CRS_ELAPSED_TIME                14
DEST_CITY                        0
CRS_DEP_TIME                     0
DEST                             0
DOT_CODE                         0
FL_NUMBER                        0
ORIGIN                           0
ORIGIN_CITY                      0
AIRLINE                          0
AIRLINE_DOT                      0
FL_DATE                          0
AIRLINE_CODE                     0
DIVERTED                         0
CANCELLED                        0
CRS_ARR_TIME                     0
DISTANCE                         0
dtype: int64

**STEP 10: Calculate Null Percentage**

In [14]:
null_percentage = (df.isnull().sum() / len(df)) * 100
null_percentage = null_percentage.sort_values(ascending=False)

null_percentage

CANCELLATION_CODE          97.362000
DELAY_DUE_LATE_AIRCRAFT    82.204567
DELAY_DUE_CARRIER          82.204567
DELAY_DUE_SECURITY         82.204567
DELAY_DUE_NAS              82.204567
DELAY_DUE_WEATHER          82.204567
ARR_DELAY                   2.873267
ELAPSED_TIME                2.873267
AIR_TIME                    2.873267
WHEELS_ON                   2.664800
TAXI_IN                     2.664800
ARR_TIME                    2.664733
WHEELS_OFF                  2.626867
TAXI_OUT                    2.626867
DEP_DELAY                   2.588133
DEP_TIME                    2.587167
CRS_ELAPSED_TIME            0.000467
DEST_CITY                   0.000000
CRS_DEP_TIME                0.000000
DEST                        0.000000
DOT_CODE                    0.000000
FL_NUMBER                   0.000000
ORIGIN                      0.000000
ORIGIN_CITY                 0.000000
AIRLINE                     0.000000
AIRLINE_DOT                 0.000000
FL_DATE                     0.000000
AIRLINE_CODE                0.000000
DIVERTED                    0.000000
CANCELLED                   0.000000
CRS_ARR_TIME                0.000000
DISTANCE                    0.000000
dtype: float64

**STEP 11: Create Null Analysis Report**

In [15]:
null_report = pd.DataFrame({
    "Null_Count": df.isnull().sum(),
    "Null_Percentage": (df.isnull().sum() / len(df)) * 100
})

null_report = null_report.sort_values(by="Null_Percentage", ascending=False)

null_report

                         Null_Count  Null_Percentage
CANCELLATION_CODE           2920860        97.362000
DELAY_DUE_LATE_AIRCRAFT     2466137        82.204567
DELAY_DUE_CARRIER           2466137        82.204567
DELAY_DUE_SECURITY          2466137        82.204567
DELAY_DUE_NAS               2466137        82.204567
DELAY_DUE_WEATHER           2466137        82.204567
ARR_DELAY                     86198         2.873267
ELAPSED_TIME                  86198         2.873267
AIR_TIME                      86198         2.873267
WHEELS_ON                     79944         2.664800
TAXI_IN                       79944         2.664800
ARR_TIME                      79942         2.664733
WHEELS_OFF                    78806         2.626867
TAXI_OUT                      78806         2.626867
DEP_DELAY                     77644         2.588133
DEP_TIME                      77615         2.587167
CRS_ELAPSED_TIME                 14         0.000467
DEST_CITY                         0         0.000000
CRS_DEP_TIME                      0         0.000000
DEST                              0         0.000000
DOT_CODE                          0         0.000000
FL_NUMBER                         0         0.000000
ORIGIN                            0         0.000000
ORIGIN_CITY                       0         0.000000
AIRLINE                           0         0.000000
AIRLINE_DOT                       0         0.000000
FL_DATE                           0         0.000000
AIRLINE_CODE                      0         0.000000
DIVERTED                          0         0.000000
CANCELLED                         0         0.000000
CRS_ARR_TIME                      0         0.000000
DISTANCE                          0         0.000000

In [16]:
null_report.to_csv("AirFly_Insights/reports/null_analysis_report.csv")

**SAMPLING & OPTIMIZATION**

**STEP 12: Check Memory Usage**

In [20]:
df.memory_usage(deep=True).sum() / (1024**2)

np.float64(1990.9640283584595)

**STEP 13: Optimize Memory (Convert Object → Category)**

In [22]:
for col in categorical_cols:
    df[col] = df[col].astype('category')

In [23]:
df.memory_usage(deep=True).sum() / (1024**2)

np.float64(566.7607955932617)

**STEP 14: Create Sample Dataset (10%)**

In [24]:
sample_df = df.sample(frac=0.1, random_state=42)
sample_df.shape

(300000, 32)

In [26]:
import os

# Create the directory if it does not exist
os.makedirs("AirFly_Insights/data/sample", exist_ok=True)

sample_df.to_csv("AirFly_Insights/data/sample/sample_dataset.csv", index=False)

In [ ]:
df.describe()

,DOT_CODE,FL_NUMBER,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
count,947582.000000,947582.000000,947582.000000,923090.000000,923082.000000,922720.000000,922720.000000,922366.000000,922366.000000,947582.000000,922366.000000,920435.000000,947582.000000,947582.000000,947576.000000,920435.000000,920435.000000,947582.000000,169237.000000,169237.000000,169237.000000,169237.000000,169237.000000
mean,19976.438107,2510.555507,1326.932735,1329.580916,10.108796,16.639585,1352.222531,1462.525013,7.682737,1490.726743,1466.500963,4.252219,0.026351,0.002296,142.209746,136.572009,112.262191,808.901811,24.547203,3.904767,13.207071,0.148626,25.377477
std,377.285118,1746.017574,485.973150,499.477203,48.844681,9.205955,501.040502,527.227430,6.274900,511.439774,531.845008,50.826885,0.160178,0.047865,71.502839,71.651735,69.718878,587.600192,70.910825,32.253816,33.131658,3.407085,55.304930
min,19393.000000,1.000000,1.000000,1.000000,-82.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-96.000000,0.000000,0.000000,20.000000,15.000000,8.000000,29.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19790.000000,1050.000000,915.000000,915.000000,-6.000000,11.000000,931.000000,1049.000000,4.000000,1107.000000,1052.000000,-16.000000,0.000000,0.000000,90.000000,84.000000,61.000000,377.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,19930.000000,2152.000000,1320.000000,1322.000000,-2.000000,14.000000,1335.000000,1501.000000,6.000000,1516.000000,1504.000000,-7.000000,0.000000,0.000000,125.000000,120.000000,95.000000,651.000000,4.000000,0.000000,0.000000,0.000000,0.000000
75%,20368.000000,3794.000000,1730.000000,1739.000000,6.000000,19.000000,1753.000000,1909.000000,9.000000,1919.000000,1913.000000,7.000000,0.000000,0.000000,172.000000,167.000000,142.000000,1045.000000,23.000000,0.000000,17.000000,0.000000,30.000000
max,20452.000000,8815.000000,2359.000000,2400.000000,2690.000000,184.000000,2400.000000,2400.000000,240.000000,2400.000000,2400.000000,2685.000000,1.000000,1.000000,695.000000,722.000000,667.000000,5812.000000,2685.000000,1398.000000,1468.000000,377.000000,2010.000000

In [ ]:
null_report = df.isnull().sum().sort_values(ascending=False)
null_report

CANCELLATION_CODE          922612
ELAPSED_TIME                27147
AIR_TIME                    27147
WHEELS_ON                   25216
TAXI_IN                     25216
ARR_TIME                    25216
WHEELS_OFF                  24862
TAXI_OUT                    24862
DEP_TIME                    24492
CRS_ELAPSED_TIME                6
ORIGIN_CITY                     0
ORIGIN                          0
FL_DATE                         0
AIRLINE                         0
AIRLINE_DOT                     0
AIRLINE_CODE                    0
DEP_DELAY                       0
DEST                            0
DEST_CITY                       0
CRS_DEP_TIME                    0
DOT_CODE                        0
FL_NUMBER                       0
ARR_DELAY                       0
CRS_ARR_TIME                    0
DIVERTED                        0
CANCELLED                       0
DISTANCE                        0
DELAY_DUE_CARRIER               0
DELAY_DUE_WEATHER               0
DELAY_DUE_NAS                   0
DELAY_DUE_SECURITY              0
DELAY_DUE_LATE_AIRCRAFT         0
dtype: int64

In [ ]:
null_percent = (df.isnull().sum() / len(df)) * 100
null_percent.sort_values(ascending=False)

CANCELLATION_CODE          97.364872
ELAPSED_TIME                2.864871
AIR_TIME                    2.864871
WHEELS_ON                   2.661089
TAXI_IN                     2.661089
ARR_TIME                    2.661089
WHEELS_OFF                  2.623731
TAXI_OUT                    2.623731
DEP_TIME                    2.584684
CRS_ELAPSED_TIME            0.000633
ORIGIN_CITY                 0.000000
ORIGIN                      0.000000
FL_DATE                     0.000000
AIRLINE                     0.000000
AIRLINE_DOT                 0.000000
AIRLINE_CODE                0.000000
DEP_DELAY                   0.000000
DEST                        0.000000
DEST_CITY                   0.000000
CRS_DEP_TIME                0.000000
DOT_CODE                    0.000000
FL_NUMBER                   0.000000
ARR_DELAY                   0.000000
CRS_ARR_TIME                0.000000
DIVERTED                    0.000000
CANCELLED                   0.000000
DISTANCE                    0.000000
DELAY_DUE_CARRIER           0.000000
DELAY_DUE_WEATHER           0.000000
DELAY_DUE_NAS               0.000000
DELAY_DUE_SECURITY          0.000000
DELAY_DUE_LATE_AIRCRAFT     0.000000
dtype: float64

In [ ]:
null_percent.to_csv("null_analysis_report.csv")

In [ ]:
df.isnull().sum().sort_values(ascending=False)
(df.isnull().sum()/len(df)) * 100

FL_DATE                     0.000000
AIRLINE                     0.000000
AIRLINE_DOT                 0.000000
AIRLINE_CODE                0.000000
DOT_CODE                    0.000000
FL_NUMBER                   0.000000
ORIGIN                      0.000000
ORIGIN_CITY                 0.000000
DEST                        0.000000
DEST_CITY                   0.000000
CRS_DEP_TIME                0.000000
DEP_TIME                    2.584684
DEP_DELAY                   0.000000
TAXI_OUT                    2.623731
WHEELS_OFF                  2.623731
WHEELS_ON                   2.661089
TAXI_IN                     2.661089
CRS_ARR_TIME                0.000000
ARR_TIME                    2.661089
ARR_DELAY                   0.000000
CANCELLED                   0.000000
CANCELLATION_CODE          97.364872
DIVERTED                    0.000000
CRS_ELAPSED_TIME            0.000633
ELAPSED_TIME                2.864871
AIR_TIME                    2.864871
DISTANCE                    0.000000
DELAY_DUE_CARRIER           0.000000
DELAY_DUE_WEATHER           0.000000
DELAY_DUE_NAS               0.000000
DELAY_DUE_SECURITY          0.000000
DELAY_DUE_LATE_AIRCRAFT     0.000000
dtype: float64

In [ ]:
df.duplicated().sum()
df=df.drop_duplicates()

In [ ]:
df.memory_usage(deep=True)

Index                           132
FL_DATE                     7580656
AIRLINE                    64996118
AIRLINE_DOT                68786446
AIRLINE_CODE               48326682
DOT_CODE                    7580656
FL_NUMBER                   7580656
ORIGIN                     49274264
ORIGIN_CITY                58852750
DEST                       49274264
DEST_CITY                  58863777
CRS_DEP_TIME                7580656
DEP_TIME                    7580656
DEP_DELAY                   7580656
TAXI_OUT                    7580656
WHEELS_OFF                  7580656
WHEELS_ON                   7580656
TAXI_IN                     7580656
CRS_ARR_TIME                7580656
ARR_TIME                    7580656
ARR_DELAY                   7580656
CANCELLED                    947706
CANCELLATION_CODE          30772084
DIVERTED                     947706
CRS_ELAPSED_TIME            7580656
ELAPSED_TIME                7580656
AIR_TIME                    7580656
DISTANCE                    7580656
DELAY_DUE_CARRIER           7580656
DELAY_DUE_WEATHER           7580656
DELAY_DUE_NAS               7580656
DELAY_DUE_SECURITY          7580656
DELAY_DUE_LATE_AIRCRAFT     7580656
dtype: int64

In [ ]:
for col in df.select_dtypes(include='object').columns:
  df[col] = df[col].astype('category')

for col in df.select_dtypes(include=['int64']).columns:
  df[col]=pd.to_numeric(df[col],downcast='integer')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 947582 entries, 0 to 947581
Data columns (total 32 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   FL_DATE                  947582 non-null  datetime64[ns]
 1   AIRLINE                  947582 non-null  category
 2   AIRLINE_DOT              947582 non-null  category
 3   AIRLINE_CODE             947582 non-null  category
 4   DOT_CODE                 947582 non-null  int16
 5   FL_NUMBER                947582 non-null  int16
 6   ORIGIN                   947582 non-null  category
 7   ORIGIN_CITY              947582 non-null  category
 8   DEST                     947582 non-null  category
 9   DEST_CITY                947582 non-null  category
 10  CRS_DEP_TIME             947582 non-null  int16
 11  DEP_TIME                 923090 non-null  float64
 12  DEP_DELAY                947582 non-null  float64
 13  TAXI_OUT                 922720 non-null  float64
 14  WHEELS_OFF               922720 non-null  float64
 15  WHEELS_ON                922366 non-null  float64
 16  TAXI_IN                  922366 non-null  float64
 17  CRS_ARR_TIME             947582 non-null  int16
 18  ARR_TIME                 922366 non-null  float64
 19  ARR_DELAY                947582 non-null  float64
 20  CANCELLED                947582 non-null  category
 21  CANCELLATION_CODE        24970 non-null   category
 22  DIVERTED                 947582 non-null  category
 23  CRS_ELAPSED_TIME         947576 non-null  float64
 24  ELAPSED_TIME             920435 non-null  float64
 25  AIR_TIME                 920435 non-null  float64
 26  DISTANCE                 947582 non-null  float64
 27  DELAY_DUE_CARRIER        947582 non-null  float64
 28  DELAY_DUE_WEATHER        947582 non-null  float64
 29  DELAY_DUE_NAS            947582 non-null  float64
 30  DELAY_DUE_SECURITY       947582 non-null  float64
 31  DELAY_DUE_LATE_AIRCRAFT  947582 non-null  float64
dtypes: category(10), datetime64[ns](1), float64(17), int16(4)
memory usage: 150.1 MB